config/routes.rb
LinkerApp::Application.routes.draw do
  resources :visitors

  resources :link_items

  get ':short_name', to: "link_items#redirector"

  

end

app/models/link_item.rb
class LinkItem < ActiveRecord::Base
  has_many :visitors
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :link_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/link_items_controller.rb
class LinkItemsController < ApplicationController
  before_action :set_link_item, only: [:show, :edit, :update, :destroy]

  def redirector
    short_name = params[:short_name]
    li = LinkItem.find_by_short_name(short_name)
 
    v = Visitor.new({ :ip_address => request.remote_ip,
         :referrer => request.referer })
    li.visitors << v
 
    redirect_to li.original_url
  end
  # GET /link_items
  # GET /link_items.json
  def index
    @link_items = LinkItem.all
  end

  # GET /link_items/1
  # GET /link_items/1.json
  def show
  end

  # GET /link_items/new
  def new
    @link_item = LinkItem.new
  end

  # GET /link_items/1/edit
  def edit
  end

  # POST /link_items
  # POST /link_items.json
  def create
    @link_item = LinkItem.new(link_item_params)

    respond_to do |format|
      if @link_item.save
        format.html { redirect_to @link_item, notice: 'Link item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @link_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_items/1
  # PATCH/PUT /link_items/1.json
  def update
    respond_to do |format|
      if @link_item.update(link_item_params)
        format.html { redirect_to @link_item, notice: 'Link item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_items/1
  # DELETE /link_items/1.json
  def destroy
    @link_item.destroy
    respond_to do |format|
      format.html { redirect_to link_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_item
      @link_item = LinkItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_item_params
      params.require(:link_item).permit(:original_url, :short_name, :password, :needs_email)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visitor }
      else
        format.html { render action: 'new' }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:ip_address, :email_address, :referrer, :link_item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_items_helper.rb
module LinkItemsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LinkerApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">LinkerApp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/link_items/_form.html.erb
<%= form_for @link_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :original_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :original_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :short_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :short_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :needs_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :needs_email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                link_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/link_items/edit.html.erb
<h1>Editing link_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_item %> |
<%= link_to 'Back', link_items_path %>

app/views/link_items/index.html.erb
<h1>Listing link_items</h1>

<table>
  <thead>
    <tr>
      <th>Original url</th>
      <th>Short name</th>
      <th>Password</th>
      <th>Needs email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @link_items.each do |link_item| %>
      <tr>
        <td><%= link_item.original_url %></td>
        <td><%= link_item.short_name %></td>
        <td><%= link_item.password %></td>
        <td><%= link_item.needs_email %></td>
        <td><%= link_to 'Show', link_item %></td>
        <td><%= link_to 'Edit', edit_link_item_path(link_item) %></td>
        <td><%= link_to 'Destroy', link_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link item', new_link_item_path %>

app/views/link_items/new.html.erb
<h1>New link_item</h1>

<%= render 'form' %>

<%= link_to 'Back', link_items_path %>

app/views/link_items/show.html.erb
<%- model_class = LinkItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:original_url) %>:</strong></dt>
  <dd><%= @link_item.original_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_name) %>:</strong></dt>
  <dd><%= @link_item.short_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @link_item.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:needs_email) %>:</strong></dt>
  <dd><%= @link_item.needs_email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              link_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_link_item_path(@link_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              link_item_path(@link_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/visitors/_form.html.erb
<%= form_for @visitor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ip_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ip_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :referrer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :referrer, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link_item_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link_item_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                visitors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visitors/index.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ip_address) %></th>
      <th><%= model_class.human_attribute_name(:email_address) %></th>
      <th><%= model_class.human_attribute_name(:referrer) %></th>
      <th><%= model_class.human_attribute_name(:link_item_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= link_to visitor.id, visitor_path(visitor) %></td>
        <td><%= visitor.ip_address %></td>
        <td><%= visitor.email_address %></td>
        <td><%= visitor.referrer %></td>
        <td><%= link_to(visitor.link_item,
                  link_item_path(visitor.link_item)) %></td>
        <td><%=l visitor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_visitor_path(visitor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      visitor_path(visitor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_visitor_path,
            :class => 'btn btn-primary' %>

app/views/visitors/new.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visitors/show.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ip_address) %>:</strong></dt>
  <dd><%= @visitor.ip_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email_address) %>:</strong></dt>
  <dd><%= @visitor.email_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:referrer) %>:</strong></dt>
  <dd><%= @visitor.referrer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link_item_id) %>:</strong></dt>
  <dd><%= @visitor.link_item_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              visitors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_visitor_path(@visitor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              visitor_path(@visitor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>